In [1]:
import numpy as np
import pandas as pd
import cv2

In [ ]:
img=cv2.imread("Test/Before.png",-1)
mous=cv2.imread("Train/mustache.png",-1)
glasses=cv2.imread("Train/glasses.png",-1)
face_cascade=cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")
eyes_cascade=cv2.CascadeClassifier("haarcascade_mcs_eye.xml")
nose_cascade=cv2.CascadeClassifier("haarcascade_mcs_nose.xml")

eyes=eyes_cascade.detectMultiScale(img,1.3,5)
nose=nose_cascade.detectMultiScale(img,1.3,5)
faces=face_cascade.detectMultiScale(img,1.3,5)

for x,y,w,h in nose:
    offset=10
    offsety=40
    extra=10
    #cv2.rectangle(img,(x,y+offsety),(x+w+offset,y+h+offset),(0,0,0),2)
    img1=img[y+offsety-extra:y+h+offset+extra,x:x+w+offset]
    img2=cv2.resize(mous,(w+offset,h+offset+2*extra-offsety))
    w1,h1,z=img1.shape
    for i in range(0,w1):
        for j in range(0,h1):
            if img2[i,j][3] != 0:
                img1[i,j] = img2[i, j]
    img[y+offsety-extra:y+h+offset+extra,x:x+w+offset]=img1

for eye in eyes:
    x,y,w,h=eye
    offset=20
    offsety=20
    img1=img[y-offsety:y+h+offsety,x-offset:x+w+offset]
    #cv2.rectangle(img,(x-offset,y),(x+w+offset,y+h),(0,0,0),2)
    #cv2.imshow("image",img)
    img2=cv2.resize(glasses,(w+2*offset,h+2*offsety))
    #cv2.imshow("image",img2)
    w1,h1,z=img1.shape
    for i in range(0,w1):
        for j in range(0,h1):
            if img2[i,j][3] != 0:
                img1[i,j] = img2[i, j]
    img[y-offsety:y+h+offsety,x-offset:x+w+offset]=img1
    #cv2.imshow("image",img)
    
px = np.array(img)
#print(px.ndim)
print(px)
p = px.flatten()
#print(p)
np.savetxt('Pixel.csv', p, delimiter=',')
cv2.imwrite("After.png", img)
cv2.waitKey(0) 
cv2.destroyAllWindows()

[[[180 202 219 255]
  [181 203 220 255]
  [180 202 219 255]
  ...
  [175 197 215 255]
  [174 199 216 255]
  [173 199 214 255]]

 [[180 202 219 255]
  [181 203 220 255]
  [180 202 219 255]
  ...
  [176 198 215 255]
  [175 199 216 255]
  [173 199 214 255]]

 [[180 202 219 255]
  [181 203 220 255]
  [180 202 219 255]
  ...
  [176 198 215 255]
  [175 199 216 255]
  [173 199 214 255]]

 ...

 [[  1   2   6 255]
  [  0   1   5 255]
  [  1   2   6 255]
  ...
  [ 21  21  27 255]
  [ 20  20  26 255]
  [ 10  10  17 255]]

 [[  2   3   7 255]
  [  1   2   6 255]
  [  0   1   5 255]
  ...
  [ 16  16  22 255]
  [ 15  15  21 255]
  [ 16  16  22 255]]

 [[  2   3   7 255]
  [  0   1   5 255]
  [  0   1   5 255]
  ...
  [ 13  13  19 255]
  [ 15  15  21 255]
  [ 15  15  22 255]]]
